### ISSUE TITLE
현재 무한로딩에 빠져있습니다.

### ISSUE THREAD

**Issue by JYPgoogle** [Escaper-Park/unofficial_chzzk_android_tv#19]
라이브 목록은 정상적으로 뜨는데 라이브를 클릭하면 로딩 중에서 화면 변화가 없습니다.

캐시삭제, 데이터 삭제, 앱 삭제 후 재설치를 해봤으나 변화가 없어 이슈 작성합니다.

항상 잘사용하고 있습니다. 저만 그런 증상이 아니어서 해결중이길 바랍니다..ㅠ

**Comment by Escaper-Park** [comment]
'저만 그런 증상이 아니어서 해결중이길 바랍니다' -> 다른 분들도 똑같은 증상이 있다는 건가요?

방금 티비 켜서 확인해봤는데 저는 재생이 잘됩니다만... 혹시 같은 네트워크를 사용하시는 분들이 똑같이 안되는 거라면
사용하시는 네트워크(공유기 등) 환경 문제일 가능성이 큽니다.

티비에 VPN 같은 것이 설치되어 있는지, 공유기에는 문제가 없는지 확인해보세요.

(저녁 7시 이후에 추가적으로 답변 드리겠습니다)

**Comment by Escaper-Park** [comment]
방금 또 확인해봤는데 (오후 6시 55분) 정상 작동합니다. 네트워크 환경을 다시 확인해보세요.

증상이 계속 지속된다면 (안드로이드 설정 - 기기 환경설정 - 다시 시작) 으로 기기 재부팅 시도해보세요.

**Comment by JYPgoogle** [comment]
> 방금 또 확인해봤는데 (오후 6시 55분) 정상 작동합니다. 네트워크 환경을 다시 확인해보세요.
> 
> 증상이 계속 지속된다면 (안드로이드 설정 - 기기 환경설정 - 다시 시작) 으로 기기 재부팅 시도해보세요.

답변 감사합니다.. 지우고 깔고 반복해도 안되던게 기기 다시시작하니까 되네요..ㅠㅡㅜ

**Comment by coderhyme** [comment]
저도 동일한 증상이 있더군요 크롬캐스트에 설치해서 사용할땐 문제가 없는데 다른 tv에서 발생하고 일정시간 방송 변경하면서 사용하면 항상 발생하고 이 상태에서는 유튜브나 다른 앱으로 영상실행하면 크래시가 나네요. 디바이스를 재실행하거나 치지직 앱을 강제종료하면 복구되는 듯합니다. 특정 기기에서만 발생하는것으로 보이네요

**Comment by Escaper-Park** [comment]
> 저도 동일한 증상이 있더군요 크롬캐스트에 설치해서 사용할땐 문제가 없는데 다른 tv에서 발생하고 일정시간 방송 변경하면서 사용하면 항상 발생하고 이 상태에서는 유튜브나 다른 앱으로 영상실행하면 크래시가 나네요. 디바이스를 재실행해야 해결되는것으로 보입니다. 특정 기기에서만 발생하나보네요.

특정 기기 문제라기 보다는 저사양 기기(또는 여러 앱을 동시에 사용하시는 분들)의 메모리 문제라고 말할 수 있겠습니다. 

저사양 기기 사용자 분들이 구버전 앱에서 VOD를 재생할 때, 영상 길이가 긴 영상을 메모리 문제로 재생하지 못해서 Andoird의 largeHeap 설정을 켜놨습니다. 이 설정은 메모리의 Heap영역 사용 크기 최대치를 늘려주는 옵션인데 이게 문제가 많습니다.

> Whether the application's processes are created with a large Dalvik heap. This applies to all processes created for the application. It only applies to the first application loaded into a process. If you're using a shared user ID to let multiple applications use a process, _**they all must use this option consistently to avoid unpredictable results.**_
_**Most apps don't need this and instead focus on reducing their overall memory usage for improved performance.**_ Enabling this also doesn't guarantee a fixed increase in available memory, because some devices are constrained by their total available memory.
[https://developer.android.com/guide/topics/manifest/application-element#largeHeap](https://developer.android.com/guide/topics/manifest/application-element#largeHeap)

이 옵션은 기본적으로 안드로이드에서 사용을 권장하지 않고 앱 최적화로 메모리 사용량을 줄이라고 되어있습니다. 그리고 다른 앱 구동에 영향을 미칩니다.

하지만 이때는 치지직 다시보기 업데이트가 mp4 인코딩으로 제공되던 시절이었고, 긴 시간의 mp4 영상을 저사양 기기 유저도 사용할 수 있게 하려면 어쩔 수 없이 사용해야 했습니다 (이 부분은 앱 최적화로 바꿀 수 없는 부분이기에). 지금은 다시보기 인코딩 방식이 바뀌어서 largeHeap 옵션을 꺼도 재생이 잘될겁니다. 

하지만 이 옵션을 꺼버리면 멀티뷰 구동에 문제가 많이 생깁니다 (멀티뷰도 메모리를 많이 사용하기 때문에). 사실 멀티뷰를 포기하면 앱 구조가 매우 단순해져서 안정성을 크게 높일 수 있습니다만, 멀티뷰 기능을 원하시는 분들이 워낙 많으셔서 어쩔 수 없는 부분인 것 같습니다. 멀티뷰 기능 없는 버전으로 분리해서 내놓을 수 있겠지만 이건 비효율적이라고 생각됩니다 (사실 제가 귀찮아서...).

조만간 정식 앱이 출시된다고 하니 조금 불편하시더라도 양해를 부탁드립니다.

**Comment by coderhyme** [comment]
말씀하신대로 해당 옵션을 빼고 빌드해서 테스트해봤는데 거의 발생 하지 않았습니다.
감사합니다.
